# Generated by Django 4.1.3 on 2023-03-20 22:31

from django.conf import settings
from django.db import migrations, models
import notification.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('danger', 'danger'), ('warning', 'warning'), ('info', 'info'), ('success', 'success')], default='info', max_length=10, null=True)),
                ('icon', models.CharField(blank=True, default='bell-fill', max_length=55, null=True)),
                ('title', models.CharField(max_length=254)),
                ('message', models.TextField()),
                ('for_user', models.BooleanField(db_index=True, default=False)),
                ('viewed', models.BooleanField(db_index=True, default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('users', models.ManyToManyField(blank=True, default=notification.models.all_users, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
