# Generated by Django 4.1.3 on 2023-03-25 20:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0005_alter_notification_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='viewed',
        ),
        migrations.AddField(
            model_name='notification',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='viewed_notification', to=settings.AUTH_USER_MODEL),
        ),
    ]
