# Generated by Django 4.1.3 on 2022-12-22 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('genericm2m', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatedobject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='relatedobject',
            name='object_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_%(class)s', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='relatedobject',
            name='parent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_%(class)s', to='contenttypes.contenttype'),
        ),
    ]
