# Generated by Django 4.1 on 2022-09-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='resume',
            field=models.TextField(blank=True, help_text='Use 1000 words only. To be pulished in the website.', max_length=1000, null=True),
        ),
    ]
